#    logo = "home"

#    showCategoriesMenu = false
#    showTagsMenu = true

#    [usersettings]
#        sidebar = "right" # left/right

    [colors]
        [colors.light]
            bg = "#f4cccc"
            bg_card = "#FFFFFF"