#    logo = "bug"

#    showCategoriesMenu = false
#    showTagsMenu = true

#    [usersettings]
#        searchProvider = "fuse" # fuse/meilisearch/algolia/typesense
#        sidebar = "left" # left/right
#        imageLink = external

    