#    logo = "home"

#    showCategoriesMenu = false
#    showTagsMenu = true

#    [usersettings]
#        sidebar = "right" # left/right
#        imageLink = external

    [colors]
        [colors.light]
            bg = "#d7d41f"
            bg_card = "#FFFFFF"